# Generated by Django 2.2.4 on 2019-08-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('permissions', models.CharField(blank=True, choices=[('0', 'Collaborator'), ('1', 'Admin')], default='0', max_length=1)),
            ],
        ),
    ]
